### ISSUE TITLE
Could not pass event error.

### ISSUE THREAD

**Issue by DrHeretic** [promcteam/promccore#11]
![image](https://user-images.githubusercontent.com/88398845/211174345-228aa3fb-8c86-4613-922c-25caa828ab44.png)

![image](https://user-images.githubusercontent.com/88398845/211174367-7dae0460-2224-48b7-b6a6-7b23ee205aa9.png)

Latest version

**Comment by DrHeretic** [comment]
Happens just as coming into the test server with the updated promccore.

**Comment by Travja** [comment]
Humpf. That looks familiar but I guess I only propelling fixed it on 1.19.
