### ISSUE TITLE
Add Simplified Chinese translation

### ISSUE THREAD

**Issue by Beafty** [promcteam/promccore#14]
[messages_cn .txt](https://github.com/promcteam/promccore/files/10714112/messages_cn.txt)
![image](https://user-images.githubusercontent.com/40541355/218269789-401e7031-025c-4e33-821d-4da27551809e.png)
make it looks like this

**Comment by Travja** [comment]
I don't know Chinese, so I'm not sure what the issue is. Could you elaborate?

**Comment by Beafty** [comment]
It sounds more like an enhancement
![image](https://user-images.githubusercontent.com/40541355/218272289-e513baf8-188d-40cd-957a-ee6f51622d43.png)

**Comment by Travja** [comment]
Oh so you've provided updated translations. I see.

**Comment by Travja** [comment]
I haven't pushed the update for this yet, but will shortly.
