### ISSUE TITLE
YAML & JSON(Maybe something else) Parser

### ISSUE THREAD

**Issue by tangjin0418** [promcteam/promccore#15]
![image](https://user-images.githubusercontent.com/55261514/220614611-9fe85d2b-68f8-4665-94e6-0ec7d1232ce8.png)
As the code shows, your Parser(s) share a variable `i`,
this will cause issues when async.
Please make that parser an Object or do something else.

Like:
![image](https://user-images.githubusercontent.com/55261514/220615071-4dfe2c95-ca59-445e-87af-056241091331.png)

**Comment by Travja** [comment]
Hmm. Yeah that's interesting. I didn't write the YAMLParser class, but that definitely should be adjusted.

**Comment by tangjin0418** [comment]
By the way
The YAML parse countSpace should also be changed to:
![image](https://user-images.githubusercontent.com/55261514/220656435-9a3800b6-6d1c-4c0d-af70-89bef9a1dafc.png)
Otherwise, if the key contains spaces that will be counted too.
