### ISSUE TITLE
After using the latest version, there are the same items in the inventory bar, and it will bounce back when sliding with the pulley

### ISSUE THREAD

**Issue by CCjun6** [promcteam/promccore#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The player puts the same item in the inventory, such as a grass block
Then use the mouse wheel to scroll
You will find that you can’t slide and will always bounce back

### Expected Behavior

Hope to fix it soon

### Environment

```markdown
- Server Software:
- ProRPGItems Version:1.0.6-r0.1
- ProMCCore Version:1.0.6-r0.1
- Plugins: pupur 1.20.1
```

### latest.log

no

### Anything else?

no

**Comment by Sentropic** [comment]
Fixed in 1b99142624aa3866e62990a452538dda59a1f602
