### ISSUE TITLE
It doesn't seem to support mythicmobs5.1.1

### ISSUE THREAD

**Issue by 1233Ao** [promcteam/promccore#9]
[111.txt](https://github.com/promcteam/promccore/files/9278685/111.txt)

**Comment by Travja** [comment]
This really isn't much of a bug report... But this error is actually suggesting that you're not running MythicMobs 5 at all, but rather MythicMobs 4. Or you may at least have Mythic Mobs 4 still in your plugins directory and so it's loading up the wrong hook class. If you could provide more details like your plugin list, a full startup log, and any other relevant information, that would be great.
